// Generated by youtube/scripts/export_portuguese_archive_for_site.py
// Do not edit by hand; update youtube/content-model/taxonomy.json or the editorial CSVs and regenerate.

export interface PortugueseCourse {
	slug: string;
	title: string;
	coverTitle: string;
	description: string;
	url: string;
	thumbnail: string;
	videoCount: number;
	views: number;
	topic: string;
	kind: string;
}

export interface PortugueseTalk {
	title: string;
	url: string;
	thumbnail: string;
	collection: string;
	group: string;
	kind: string;
	topic: string;
	score: number;
	views: number;
	durationSeconds: number;
	duration: string;
}

export interface PortuguesePlaylist {
	title: string;
	description: string;
	url: string;
	thumbnail: string;
	videoCount: number;
}

export const portugueseArchive = {
	updatedAt: "2026-07-11T00:25:41Z",
	intro: "Durante muitos anos eu ensinei Python, Django, design de software, carreira e autonomia para desenvolvedores brasileiros. Este acervo reúne parte pública desse período: cursos, séries e palestras que ainda podem ajudar quem está trilhando esse caminho.",
	courses: [
	{
		"slug": "welcome-to-the-django",
		"title": "Welcome to the Django",
		"coverTitle": "Welcome to the Django",
		"description": "Uma trilha extensa sobre Django, Python, web, prática profissional e autonomia no desenvolvimento.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxczQsE7L5H9RXTcNFjx3U55",
		"thumbnail": "https://i.ytimg.com/vi/uMNmrhHPkfQ/hqdefault.jpg",
		"videoCount": 121,
		"views": 43248,
		"topic": "Django/Python",
		"kind": "Curso"
	},
	{
		"slug": "python-power",
		"title": "Python Power",
		"coverTitle": "Python Power",
		"description": "Fundamentos e prática de Python para ganhar fluência, clareza e confiança ao programar.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxfLqg6644MVgUrvgAi4uL8J",
		"thumbnail": "https://i.ytimg.com/vi/YpDBtT-Dt2c/hqdefault.jpg",
		"videoCount": 23,
		"views": 7135,
		"topic": "Python",
		"kind": "Curso"
	},
	{
		"slug": "refatoracao-na-pratica",
		"title": "Refatoração na Prática",
		"coverTitle": "Refatoração na Prática",
		"description": "Aulas sobre evolução de código, design incremental e técnicas para melhorar software existente.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxfTqEvicb9dqcbj-eCOFhhj",
		"thumbnail": "https://i.ytimg.com/vi/TCVpXFm80gU/hqdefault.jpg",
		"videoCount": 34,
		"views": 1996,
		"topic": "Refatoração",
		"kind": "Curso"
	},
	{
		"slug": "orientacao-a-objetos-na-pratica",
		"title": "Orientação a Objetos na Prática",
		"coverTitle": "Orientação a Objetos na Prática",
		"description": "Uma abordagem prática de orientação a objetos para organizar comportamento e reduzir complexidade.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxemNCYYvDUw0wRsMiN7aX1m",
		"thumbnail": "https://i.ytimg.com/vi/lrQOL7Lpdtw/hqdefault.jpg",
		"videoCount": 23,
		"views": 2627,
		"topic": "POO",
		"kind": "Curso"
	},
	{
		"slug": "design-de-api-na-pratica",
		"title": "Design de API na Prática",
		"coverTitle": "Design de API na Prática",
		"description": "Uma série sobre desenho, evolução e consumo de APIs com mais clareza e menos gambiarra.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxdD1CXDeEymwI1S9wlcsmYo",
		"thumbnail": "https://i.ytimg.com/vi/3trE61xKXXk/hqdefault.jpg",
		"videoCount": 9,
		"views": 2749,
		"topic": "APIs",
		"kind": "Curso"
	},
	{
		"slug": "domine-o-metodo-da-refatoracao-rapida",
		"title": "Domine o Método da Refatoração Rápida",
		"coverTitle": "Método da Refatoração Rápida",
		"description": "Um percurso sobre refatoração como método de trabalho, não como evento eventual.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxfHUETjNouzr1hyaiuljrUY",
		"thumbnail": "https://i.ytimg.com/vi/8DG_a8lPbbo/hqdefault.jpg",
		"videoCount": 16,
		"views": 508,
		"topic": "Refatoração",
		"kind": "Curso"
	},
	{
		"slug": "refatoracao-com-poo-em-codigo-legado",
		"title": "Refatoração com POO em código legado",
		"coverTitle": "Refatoração com POO em Código Legado",
		"description": "Uma trilha sobre como usar orientação a objetos para lidar com código legado.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxeEeta6ddgqUagLp_Oo_kAx",
		"thumbnail": "https://i.ytimg.com/vi/YvbREfT1YeI/hqdefault.jpg",
		"videoCount": 9,
		"views": 499,
		"topic": "Refatoração/POO",
		"kind": "Curso"
	},
	{
		"slug": "desvendando-algoritmos-para-escalar-a-performance-do-seu-codigo",
		"title": "Desvendando Algoritmos para Escalar a Performance do seu Código",
		"coverTitle": "Algoritmos para Escalar Performance",
		"description": "Uma introdução a algoritmos, performance e raciocínio sobre custo computacional.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxeGTZ7gqhU0bkPaWzge4wrj",
		"thumbnail": "https://i.ytimg.com/vi/BgcqTDeIxlU/hqdefault.jpg",
		"videoCount": 5,
		"views": 1967,
		"topic": "Indefinido",
		"kind": "Série curta"
	},
	{
		"slug": "evolucao-constante-de-codigo-usando-kata",
		"title": "Evolução constante de código usando Kata",
		"coverTitle": "Evolução de Código com Kata",
		"description": "Prática deliberada de programação usando katas para melhorar design e fluência.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxdxmtm_Kclt_NMvrWLasxgF",
		"thumbnail": "https://i.ytimg.com/vi/UG26CiuU_T0/hqdefault.jpg",
		"videoCount": 5,
		"views": 4420,
		"topic": "Indefinido",
		"kind": "Série curta"
	},
	{
		"slug": "o-ambiente-python-perfeito",
		"title": "O Ambiente Python Perfeito",
		"coverTitle": "O Ambiente Python Perfeito",
		"description": "Configuração e decisões de ambiente para trabalhar melhor com Python.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxerM2W71_WeWLuvU-O22vUj",
		"thumbnail": "https://i.ytimg.com/vi/TCfJDfC6_J4/hqdefault.jpg",
		"videoCount": 5,
		"views": 496,
		"topic": "Indefinido",
		"kind": "Série curta"
	},
	{
		"slug": "raio-x-da-orientacao-a-objetos",
		"title": "Raio-X da Orientação a Objetos",
		"coverTitle": "Raio-X da Orientação a Objetos",
		"description": "Uma série curta para entender os fundamentos por trás da orientação a objetos.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxdT8vUW3x9bd7B8PnwnHINW",
		"thumbnail": "https://i.ytimg.com/vi/a9LXgufi1e4/hqdefault.jpg",
		"videoCount": 5,
		"views": 661,
		"topic": "POO",
		"kind": "Série curta"
	},
	{
		"slug": "raio-x-do-test-driven-development",
		"title": "Raio-X do Test-Driven Development",
		"coverTitle": "Raio-X do TDD",
		"description": "Uma série curta sobre TDD, testes e feedback no desenvolvimento de software.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxe1X_B-o5bMDyNLxIBQB1q7",
		"thumbnail": "https://i.ytimg.com/vi/_YJAjxWAHsM/hqdefault.jpg",
		"videoCount": 5,
		"views": 784,
		"topic": "Indefinido",
		"kind": "Série curta"
	},
	{
		"slug": "calculando-o-valor-que-voce-gera",
		"title": "Calculando o Valor que Você Gera",
		"coverTitle": "O Valor que Você Gera",
		"description": "Uma série sobre valor, percepção de impacto e postura profissional.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxcyBcjqbmrmX_1PdDFzLgel",
		"thumbnail": "https://i.ytimg.com/vi/_itPespGuxQ/hqdefault.jpg",
		"videoCount": 5,
		"views": 400,
		"topic": "Indefinido",
		"kind": "Série curta"
	}
],
	featuredCourses: [
	{
		"slug": "welcome-to-the-django",
		"title": "Welcome to the Django",
		"coverTitle": "Welcome to the Django",
		"description": "Uma trilha extensa sobre Django, Python, web, prática profissional e autonomia no desenvolvimento.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxczQsE7L5H9RXTcNFjx3U55",
		"thumbnail": "https://i.ytimg.com/vi/uMNmrhHPkfQ/hqdefault.jpg",
		"videoCount": 121,
		"views": 43248,
		"topic": "Django/Python",
		"kind": "Curso"
	},
	{
		"slug": "python-power",
		"title": "Python Power",
		"coverTitle": "Python Power",
		"description": "Fundamentos e prática de Python para ganhar fluência, clareza e confiança ao programar.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxfLqg6644MVgUrvgAi4uL8J",
		"thumbnail": "https://i.ytimg.com/vi/YpDBtT-Dt2c/hqdefault.jpg",
		"videoCount": 23,
		"views": 7135,
		"topic": "Python",
		"kind": "Curso"
	},
	{
		"slug": "refatoracao-na-pratica",
		"title": "Refatoração na Prática",
		"coverTitle": "Refatoração na Prática",
		"description": "Aulas sobre evolução de código, design incremental e técnicas para melhorar software existente.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxfTqEvicb9dqcbj-eCOFhhj",
		"thumbnail": "https://i.ytimg.com/vi/TCVpXFm80gU/hqdefault.jpg",
		"videoCount": 34,
		"views": 1996,
		"topic": "Refatoração",
		"kind": "Curso"
	},
	{
		"slug": "orientacao-a-objetos-na-pratica",
		"title": "Orientação a Objetos na Prática",
		"coverTitle": "Orientação a Objetos na Prática",
		"description": "Uma abordagem prática de orientação a objetos para organizar comportamento e reduzir complexidade.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxemNCYYvDUw0wRsMiN7aX1m",
		"thumbnail": "https://i.ytimg.com/vi/lrQOL7Lpdtw/hqdefault.jpg",
		"videoCount": 23,
		"views": 2627,
		"topic": "POO",
		"kind": "Curso"
	},
	{
		"slug": "design-de-api-na-pratica",
		"title": "Design de API na Prática",
		"coverTitle": "Design de API na Prática",
		"description": "Uma série sobre desenho, evolução e consumo de APIs com mais clareza e menos gambiarra.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxdD1CXDeEymwI1S9wlcsmYo",
		"thumbnail": "https://i.ytimg.com/vi/3trE61xKXXk/hqdefault.jpg",
		"videoCount": 9,
		"views": 2749,
		"topic": "APIs",
		"kind": "Curso"
	}
],
	talks: [
	{
		"title": "Desenvolva softwares de qualidade NO PRAZO",
		"url": "https://www.youtube.com/watch?v=bz4qTpIJXJ0",
		"thumbnail": "https://i.ytimg.com/vi/bz4qTpIJXJ0/hqdefault.jpg",
		"collection": "Workshop: Aprenda a programar sem ser programado",
		"group": "Aulas abertas",
		"kind": "Aula aberta",
		"topic": "Indefinido",
		"score": 101,
		"views": 2823,
		"durationSeconds": 8864,
		"duration": "2h27"
	},
	{
		"title": "Entendendo por que merdas acontecem no desenvolvimento de software",
		"url": "https://www.youtube.com/watch?v=GWTYEOAGGc4",
		"thumbnail": "https://i.ytimg.com/vi/GWTYEOAGGc4/hqdefault.jpg",
		"collection": "Workshop: Aprenda a programar sem ser programado",
		"group": "Aulas abertas",
		"kind": "Aula aberta",
		"topic": "Indefinido",
		"score": 101,
		"views": 2777,
		"durationSeconds": 8265,
		"duration": "2h17"
	},
	{
		"title": "Trabalhando com testes para não ter trabalho",
		"url": "https://www.youtube.com/watch?v=hg595fgsYKs",
		"thumbnail": "https://i.ytimg.com/vi/hg595fgsYKs/hqdefault.jpg",
		"collection": "Workshop: Aprenda a programar sem ser programado",
		"group": "Aulas abertas",
		"kind": "Aula aberta",
		"topic": "Indefinido",
		"score": 100,
		"views": 2213,
		"durationSeconds": 13161,
		"duration": "3h39"
	},
	{
		"title": "#1 Workshop | Empreenda ou se Arrependa",
		"url": "https://www.youtube.com/watch?v=bqB6fCZEjLA",
		"thumbnail": "https://i.ytimg.com/vi/bqB6fCZEjLA/hqdefault.jpg",
		"collection": "Workshop: Supere o medo de empreender em 5 passos",
		"group": "Aulas abertas",
		"kind": "Aula aberta",
		"topic": "Indefinido",
		"score": 99,
		"views": 2004,
		"durationSeconds": 7653,
		"duration": "2h07"
	},
	{
		"title": "Recupere o prazer de trabalhar com programação",
		"url": "https://www.youtube.com/watch?v=sB2sO641L1A",
		"thumbnail": "https://i.ytimg.com/vi/sB2sO641L1A/hqdefault.jpg",
		"collection": "Workshop: Aprenda a programar sem ser programado",
		"group": "Aulas abertas",
		"kind": "Aula aberta",
		"topic": "Indefinido",
		"score": 99,
		"views": 1911,
		"durationSeconds": 9629,
		"duration": "2h40"
	},
	{
		"title": "Dia 01 | 03 habilidades que vão tirar a sua carreira de DEV da Estagnação",
		"url": "https://www.youtube.com/watch?v=wtQz-aeFCOI",
		"thumbnail": "https://i.ytimg.com/vi/wtQz-aeFCOI/hqdefault.jpg",
		"collection": "Workshop: Use a programação para construir seu novo normal",
		"group": "Aulas abertas",
		"kind": "Aula aberta",
		"topic": "Indefinido",
		"score": 98,
		"views": 1786,
		"durationSeconds": 8935,
		"duration": "2h28"
	},
	{
		"title": "Dia 02 | 04 estratégias para você desenvolver softwares de qualidade e dentro do prazo",
		"url": "https://www.youtube.com/watch?v=rfJjomQ4jtU",
		"thumbnail": "https://i.ytimg.com/vi/rfJjomQ4jtU/hqdefault.jpg",
		"collection": "Workshop: Use a programação para construir seu novo normal",
		"group": "Aulas abertas",
		"kind": "Aula aberta",
		"topic": "Indefinido",
		"score": 97,
		"views": 1409,
		"durationSeconds": 12201,
		"duration": "3h23"
	},
	{
		"title": "Dia 03 | Aprenda a programar com a confiança necessária para ter sucesso na programação",
		"url": "https://www.youtube.com/watch?v=IX5wSryEKGk",
		"thumbnail": "https://i.ytimg.com/vi/IX5wSryEKGk/hqdefault.jpg",
		"collection": "Workshop: Use a programação para construir seu novo normal",
		"group": "Aulas abertas",
		"kind": "Aula aberta",
		"topic": "Indefinido",
		"score": 95,
		"views": 1080,
		"durationSeconds": 12387,
		"duration": "3h26"
	},
	{
		"title": "Como encarar o maior desafio do programador?",
		"url": "https://www.youtube.com/watch?v=a-89NVaHECs",
		"thumbnail": "https://i.ytimg.com/vi/a-89NVaHECs/hqdefault.jpg",
		"collection": "🔥 Webinários com os convidados do WTTD",
		"group": "Aulas abertas",
		"kind": "Aula aberta",
		"topic": "Indefinido",
		"score": 95,
		"views": 1010,
		"durationSeconds": 6145,
		"duration": "1h42"
	},
	{
		"title": "#2 Workshop | Começar um negócio é realmente difícil?",
		"url": "https://www.youtube.com/watch?v=egJ_sX3AG1A",
		"thumbnail": "https://i.ytimg.com/vi/egJ_sX3AG1A/hqdefault.jpg",
		"collection": "Workshop: Supere o medo de empreender em 5 passos",
		"group": "Aulas abertas",
		"kind": "Aula aberta",
		"topic": "Indefinido",
		"score": 94,
		"views": 997,
		"durationSeconds": 7125,
		"duration": "1h58"
	},
	{
		"title": "#5 Workshop | Empreender é vender: Aprenda a fechar bons negócios",
		"url": "https://www.youtube.com/watch?v=rozDWzHZdlo",
		"thumbnail": "https://i.ytimg.com/vi/rozDWzHZdlo/hqdefault.jpg",
		"collection": "Workshop: Supere o medo de empreender em 5 passos",
		"group": "Aulas abertas",
		"kind": "Aula aberta",
		"topic": "Indefinido",
		"score": 92,
		"views": 666,
		"durationSeconds": 5805,
		"duration": "1h36"
	},
	{
		"title": "#3 Workshop | Como não quebrar a minha empresa no primeiro ano?",
		"url": "https://www.youtube.com/watch?v=XWhX4UfbvtQ",
		"thumbnail": "https://i.ytimg.com/vi/XWhX4UfbvtQ/hqdefault.jpg",
		"collection": "Workshop: Supere o medo de empreender em 5 passos",
		"group": "Aulas abertas",
		"kind": "Aula aberta",
		"topic": "Indefinido",
		"score": 91,
		"views": 568,
		"durationSeconds": 5126,
		"duration": "1h25"
	},
	{
		"title": "#4 Workshop | Como gerir o seu negócio para não virar escravo da burocracia?",
		"url": "https://www.youtube.com/watch?v=iaKXDIHjDeg",
		"thumbnail": "https://i.ytimg.com/vi/iaKXDIHjDeg/hqdefault.jpg",
		"collection": "Workshop: Supere o medo de empreender em 5 passos",
		"group": "Aulas abertas",
		"kind": "Aula aberta",
		"topic": "Indefinido",
		"score": 90,
		"views": 489,
		"durationSeconds": 5600,
		"duration": "1h33"
	},
	{
		"title": "Tangibilizando o impacto financeiro do que fazemos",
		"url": "https://www.youtube.com/watch?v=3LJFdpWJzG4",
		"thumbnail": "https://i.ytimg.com/vi/3LJFdpWJzG4/hqdefault.jpg",
		"collection": "Agile Trends 2015",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 106,
		"views": 9,
		"durationSeconds": 929,
		"duration": "15min29s"
	},
	{
		"title": "Trabalhando com Django para não ter trabalho",
		"url": "https://www.youtube.com/watch?v=dNJXN70Nqt0",
		"thumbnail": "https://i.ytimg.com/vi/dNJXN70Nqt0/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 105,
		"views": 15226,
		"durationSeconds": 5824,
		"duration": "1h37"
	},
	{
		"title": "Palestra AgileBeer Campinas 2019",
		"url": "https://www.youtube.com/watch?v=aK9mpC6xLqA",
		"thumbnail": "https://i.ytimg.com/vi/aK9mpC6xLqA/hqdefault.jpg",
		"collection": "AgileBeer Campinas 2019",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 104,
		"views": 15,
		"durationSeconds": 1052,
		"duration": "17min32s"
	},
	{
		"title": "Um Raio-X do Django",
		"url": "https://www.youtube.com/watch?v=K62z2lVHS_M",
		"thumbnail": "https://i.ytimg.com/vi/K62z2lVHS_M/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 103,
		"views": 7858,
		"durationSeconds": 2981,
		"duration": "49min41s"
	},
	{
		"title": "Pare de criar código que rasga dinheiro",
		"url": "https://www.youtube.com/watch?v=z0M1DEg8L0c",
		"thumbnail": "https://i.ytimg.com/vi/z0M1DEg8L0c/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 102,
		"views": 6332,
		"durationSeconds": 2709,
		"duration": "45min09s"
	},
	{
		"title": "The Walking Devs: Sobreviva ao Apocalipse Zumbi na Programação",
		"url": "https://www.youtube.com/watch?v=XVdJLNxeJhg",
		"thumbnail": "https://i.ytimg.com/vi/XVdJLNxeJhg/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 98,
		"views": 3948,
		"durationSeconds": 2228,
		"duration": "37min08s"
	},
	{
		"title": "Qual o verdadeiro trabalho do programador?",
		"url": "https://www.youtube.com/watch?v=XitVBKADfIY",
		"thumbnail": "https://i.ytimg.com/vi/XitVBKADfIY/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 98,
		"views": 3550,
		"durationSeconds": 3326,
		"duration": "55min26s"
	},
	{
		"title": "Carreira de Desenvolvedor sem Mistérios",
		"url": "https://www.youtube.com/watch?v=P9V6KPp_0DU",
		"thumbnail": "https://i.ytimg.com/vi/P9V6KPp_0DU/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 97,
		"views": 3205,
		"durationSeconds": 2782,
		"duration": "46min22s"
	},
	{
		"title": "Lifestyle Business e o Ecossistema Python",
		"url": "https://www.youtube.com/watch?v=pRflnCO82lM",
		"thumbnail": "https://i.ytimg.com/vi/pRflnCO82lM/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 96,
		"views": 2892,
		"durationSeconds": 2785,
		"duration": "46min25s"
	},
	{
		"title": "Freelancer Lifestyle",
		"url": "https://www.youtube.com/watch?v=4Vvf4IM5boE",
		"thumbnail": "https://i.ytimg.com/vi/4Vvf4IM5boE/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 96,
		"views": 2883,
		"durationSeconds": 3544,
		"duration": "59min04s"
	},
	{
		"title": "Quanto dinheiro você está perdendo por não fazer Software Livre?",
		"url": "https://www.youtube.com/watch?v=w2mPMmD_W98",
		"thumbnail": "https://i.ytimg.com/vi/w2mPMmD_W98/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 92,
		"views": 1446,
		"durationSeconds": 2187,
		"duration": "36min27s"
	},
	{
		"title": "Missões Resgate com Django",
		"url": "https://www.youtube.com/watch?v=_14c7Bu7LdY",
		"thumbnail": "https://i.ytimg.com/vi/_14c7Bu7LdY/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 92,
		"views": 1382,
		"durationSeconds": 1543,
		"duration": "25min43s"
	},
	{
		"title": "Community Overflow v2.0",
		"url": "https://www.youtube.com/watch?v=Ehx2Ea-EPZ0",
		"thumbnail": "https://i.ytimg.com/vi/Ehx2Ea-EPZ0/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 88,
		"views": 805,
		"durationSeconds": 2426,
		"duration": "40min26s"
	},
	{
		"title": "DevOpsDays Luanda:  O Caminho do Desenvolvedor Sênior",
		"url": "https://www.youtube.com/watch?v=LmcUjDDzm58",
		"thumbnail": "https://i.ytimg.com/vi/LmcUjDDzm58/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 87,
		"views": 676,
		"durationSeconds": 4443,
		"duration": "1h14"
	},
	{
		"title": "Small Acts make great Revolutions - Crafting Python and Open Source Communities in Rio de Janeiro",
		"url": "https://www.youtube.com/watch?v=lJgb5QMaQek",
		"thumbnail": "https://i.ytimg.com/vi/lJgb5QMaQek/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 85,
		"views": 484,
		"durationSeconds": 1698,
		"duration": "28min18s"
	},
	{
		"title": "Community Overflow 1.0 | Python Brasil 7",
		"url": "https://www.youtube.com/watch?v=69c6I8nNNgo",
		"thumbnail": "https://i.ytimg.com/vi/69c6I8nNNgo/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 78,
		"views": 182,
		"durationSeconds": 2088,
		"duration": "34min48s"
	}
],
	featuredTalks: [
	{
		"title": "Tangibilizando o impacto financeiro do que fazemos",
		"url": "https://www.youtube.com/watch?v=3LJFdpWJzG4",
		"thumbnail": "https://i.ytimg.com/vi/3LJFdpWJzG4/hqdefault.jpg",
		"collection": "Agile Trends 2015",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 106,
		"views": 9,
		"durationSeconds": 929,
		"duration": "15min29s"
	},
	{
		"title": "Trabalhando com Django para não ter trabalho",
		"url": "https://www.youtube.com/watch?v=dNJXN70Nqt0",
		"thumbnail": "https://i.ytimg.com/vi/dNJXN70Nqt0/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 105,
		"views": 15226,
		"durationSeconds": 5824,
		"duration": "1h37"
	},
	{
		"title": "Palestra AgileBeer Campinas 2019",
		"url": "https://www.youtube.com/watch?v=aK9mpC6xLqA",
		"thumbnail": "https://i.ytimg.com/vi/aK9mpC6xLqA/hqdefault.jpg",
		"collection": "AgileBeer Campinas 2019",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 104,
		"views": 15,
		"durationSeconds": 1052,
		"duration": "17min32s"
	},
	{
		"title": "Um Raio-X do Django",
		"url": "https://www.youtube.com/watch?v=K62z2lVHS_M",
		"thumbnail": "https://i.ytimg.com/vi/K62z2lVHS_M/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 103,
		"views": 7858,
		"durationSeconds": 2981,
		"duration": "49min41s"
	},
	{
		"title": "Pare de criar código que rasga dinheiro",
		"url": "https://www.youtube.com/watch?v=z0M1DEg8L0c",
		"thumbnail": "https://i.ytimg.com/vi/z0M1DEg8L0c/hqdefault.jpg",
		"collection": "🎤 Palestras",
		"group": "Palestras",
		"kind": "Palestra",
		"topic": "Palestras",
		"score": 102,
		"views": 6332,
		"durationSeconds": 2709,
		"duration": "45min09s"
	},
	{
		"title": "Desenvolva softwares de qualidade NO PRAZO",
		"url": "https://www.youtube.com/watch?v=bz4qTpIJXJ0",
		"thumbnail": "https://i.ytimg.com/vi/bz4qTpIJXJ0/hqdefault.jpg",
		"collection": "Workshop: Aprenda a programar sem ser programado",
		"group": "Aulas abertas",
		"kind": "Aula aberta",
		"topic": "Indefinido",
		"score": 101,
		"views": 2823,
		"durationSeconds": 8864,
		"duration": "2h27"
	}
],
	directPlaylists: [
	{
		"title": "Dicas de Programação",
		"description": "Vídeos mais curtos sobre programação, Python, Django e prática profissional.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxdnGoV8TBYzKqsm8p3PIEeQ",
		"thumbnail": "https://i.ytimg.com/vi/R6fhNjTb84w/hqdefault.jpg",
		"videoCount": 53
	},
	{
		"title": "Carreira e Empreendedorismo",
		"description": "Conversas curtas sobre carreira, autonomia, PJ, freelancing e mercado.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxe22wb--3Y4x8IH3AVSlbys",
		"thumbnail": "https://i.ytimg.com/vi/ZOYuW6Sw11c/hqdefault.jpg",
		"videoCount": 22
	},
	{
		"title": "Mercado de TI",
		"description": "Recortes e reflexões sobre trabalho, contratação e vida profissional em tecnologia.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxcw7CmT_RRw3eY0fNloEwF1",
		"thumbnail": "https://i.ytimg.com/vi/f9CbC0BA7UY/hqdefault.jpg",
		"videoCount": 20
	},
	{
		"title": "Visão Estratégica",
		"description": "Reflexões mais amplas sobre foco, autonomia, decisões e postura profissional.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxe2kDCsM9N44dLxXvgNksGe",
		"thumbnail": "https://i.ytimg.com/vi/bSQFQzoJreY/hqdefault.jpg",
		"videoCount": 32
	},
	{
		"title": "Shots",
		"description": "Cortes e vídeos rápidos do canal.",
		"url": "https://www.youtube.com/playlist?list=PLeKXYyZCJHxcDFQkYzDJOBPoWGu2Wu5-1",
		"thumbnail": "https://i.ytimg.com/vi/yfatX466oCo/hqdefault.jpg",
		"videoCount": 15
	}
],
} as const;
